version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      FLASK_ENV: development

  web:
    build: ./react-app
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    environment:
      NODE_ENV: development

  redis:
    image: "redis:alpine"
