services:
  localhost:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/sushiya-restaurant/app
    environment:
      FLASK_DEBUG: 1
      FLASK_ENV: development
      FLASK_APP: "app"
      DATABASE_URL: "sqlite:///dev.db"

  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./react-app:/react-app
